services:
  - type: web
    name: ems-backend-api
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
