/**
 * UNIVERSAL KANBAN ENGINE COMPONENT
 * Native CSS Overflow-X with Shift+Wheel & Background Click-and-Drag Scroll
 */

import React, { useRef, useState } from 'react';
import KanbanColumn from './KanbanColumn';

const getValString = (val, fallback = '') => {
  if (val === null || val === undefined) return fallback;
  if (typeof val === 'string' || typeof val === 'number') return String(val);
  if (typeof val === 'object') {
    if (typeof val.name === 'string') return val.name;
    if (typeof val.title === 'string') return val.title;
    if (typeof val.label === 'string') return val.label;
    if (typeof val.value === 'string') return val.value;
  }
  return fallback;
};

export default function KanbanEngine({
  records = [],
  moduleConfig = {},
  activePipelineStages = [],
  isFilterActive = false,
  onViewRecord = () => {},
  onEditRecord = () => {},
  onArchiveRecord = () => {},
  onMoveStage = () => {},
  canManage = true
}) {
  const scrollContainerRef = useRef(null);

  // Background Click-and-Drag Scroll State
  const [isMouseDown, setIsMouseDown] = useState(false);
  const [startX, setStartX] = useState(0);
  const [scrollLeftState, setScrollLeftState] = useState(0);

  // Requirement 2 & 8: Shift + Mouse Wheel scrolling ONLY (Normal wheel scrolls page vertically natively!)
  const handleWheel = (e) => {
    if (e.shiftKey && scrollContainerRef.current) {
      scrollContainerRef.current.scrollLeft += e.deltaY;
    }
  };

  // Requirement 5: Click-and-Drag on Kanban Background ONLY (Ignores cards, buttons, selects)
  const handleMouseDown = (e) => {
    if (
      e.target.closest('.enterprise-kanban-card') ||
      e.target.closest('button') ||
      e.target.closest('select') ||
      e.target.closest('input') ||
      e.target.closest('a')
    ) {
      return;
    }

    setIsMouseDown(true);
    setStartX(e.pageX - (scrollContainerRef.current?.offsetLeft || 0));
    setScrollLeftState(scrollContainerRef.current?.scrollLeft || 0);
  };

  const handleMouseLeave = () => {
    setIsMouseDown(false);
  };

  const handleMouseUp = () => {
    setIsMouseDown(false);
  };

  const handleMouseMove = (e) => {
    if (!isMouseDown || !scrollContainerRef.current) return;
    e.preventDefault();
    const x = e.pageX - scrollContainerRef.current.offsetLeft;
    const walk = (x - startX) * 1.5;
    scrollContainerRef.current.scrollLeft = scrollLeftState - walk;
  };

  // Dynamically map records to columns
  const autoGeneratedColumns = activePipelineStages.map(stage => {
    const stageName = getValString(stage.name);
    const stageId = getValString(stage.id);
    const stageKey = getValString(stage.key);

    const stageRecords = records.filter(r => {
      const recStatus = getValString(r.status || r.stage).toLowerCase();
      return (
        recStatus === stageName.toLowerCase() ||
        recStatus === stageId.toLowerCase() ||
        recStatus === stageKey.toLowerCase()
      );
    });

    return {
      id: stageId || stageName,
      name: stageName,
      emoji: stage.emoji || '📋',
      color: stage.color || '#0d9488',
      semanticType: stage.semanticType || 'CUSTOM',
      list: stageRecords
    };
  });

  return (
    <div className="kanban-engine-outer-wrapper" style={{ width: '100%' }}>
      <style>{`
        .kanban-scroll-container::-webkit-scrollbar {
          height: 10px !important;
          display: block !important;
        }
        .kanban-scroll-container::-webkit-scrollbar-track {
          background: #e2e8f0 !important;
          border-radius: 6px !important;
        }
        .kanban-scroll-container::-webkit-scrollbar-thumb {
          background: #0d9488 !important;
          border-radius: 6px !important;
        }
        .kanban-scroll-container::-webkit-scrollbar-thumb:hover {
          background: #0f766e !important;
        }
      `}</style>
      <div
        ref={scrollContainerRef}
        onWheel={handleWheel}
        onMouseDown={handleMouseDown}
        onMouseLeave={handleMouseLeave}
        onMouseUp={handleMouseUp}
        onMouseMove={handleMouseMove}
        className="kanban-scroll-container"
        style={{
          width: '100%',
          overflowX: 'auto',
          overflowY: 'hidden',
          WebkitOverflowScrolling: 'touch',
          paddingBottom: '14px',
          cursor: isMouseDown ? 'grabbing' : 'default',
          userSelect: isMouseDown ? 'none' : 'auto'
        }}
      >
        <div
          style={{
            display: 'flex',
            gap: '16px',
            alignItems: 'stretch',
            minWidth: 'max-content',
            paddingBottom: '4px'
          }}
        >
          {autoGeneratedColumns.map((col) => (
            <KanbanColumn
              key={col.id}
              stage={col}
              records={col.list}
              moduleConfig={moduleConfig}
              activePipelineStages={activePipelineStages}
              isFilterActive={isFilterActive}
              onViewRecord={onViewRecord}
              onEditRecord={onEditRecord}
              onArchiveRecord={onArchiveRecord}
              onMoveStage={onMoveStage}
              canManage={canManage}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
