/**
 * UNIVERSAL KANBAN ENGINE COMPONENT
 * Fixed 360px Non-Shrinking Stage Columns with Full Horizontal Scrollability across ALL Stages
 */

import React from 'react';
import KanbanColumn from './KanbanColumn';

const getValString = (val, fallback = '') => {
  if (val === null || val === undefined) return fallback;
  if (typeof val === 'string' || typeof val === 'number') return String(val);
  if (typeof val === 'object') {
    if (typeof val.name === 'string') return val.name;
    if (typeof val.title === 'string') return val.title;
    if (typeof val.label === 'string') return val.label;
    if (typeof val.value === 'string') return val.value;
  }
  return fallback;
};

export default function KanbanEngine({
  records = [],
  moduleConfig = {},
  activePipelineStages = [],
  isFilterActive = false,
  onViewRecord = () => {},
  onEditRecord = () => {},
  onArchiveRecord = () => {},
  onMoveStage = () => {},
  canManage = true
}) {
  // Dynamically map records to stage columns
  const autoGeneratedColumns = activePipelineStages.map(stage => {
    const stageName = getValString(stage.name);
    const stageId = getValString(stage.id);
    const stageKey = getValString(stage.key);

    const stageRecords = records.filter(r => {
      const recStatus = getValString(r.status || r.stage).toLowerCase();
      return (
        recStatus === stageName.toLowerCase() ||
        recStatus === stageId.toLowerCase() ||
        recStatus === stageKey.toLowerCase()
      );
    });

    return {
      id: stageId || stageName,
      name: stageName,
      emoji: stage.emoji || '📋',
      color: stage.color || '#0d9488',
      semanticType: stage.semanticType || 'CUSTOM',
      list: stageRecords
    };
  });

  return (
    <div className="kanban-engine-outer-wrapper" style={{ width: '100%', overflow: 'visible' }}>
      <style>{`
        .kanban-scroll-container::-webkit-scrollbar {
          height: 10px !important;
          display: block !important;
        }
        .kanban-scroll-container::-webkit-scrollbar-track {
          background: #e2e8f0 !important;
          border-radius: 6px !important;
        }
        .kanban-scroll-container::-webkit-scrollbar-thumb {
          background: #0d9488 !important;
          border-radius: 6px !important;
        }
        .kanban-scroll-container::-webkit-scrollbar-thumb:hover {
          background: #0f766e !important;
        }
      `}</style>
      <div
        className="kanban-scroll-container"
        style={{
          width: '100%',
          overflowX: 'auto',
          overflowY: 'hidden',
          WebkitOverflowScrolling: 'touch',
          paddingBottom: '16px',
          boxSizing: 'border-box'
        }}
      >
        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            gap: '16px',
            alignItems: 'flex-start',
            width: 'max-content',
            paddingRight: '32px',
            paddingBottom: '4px'
          }}
        >
          {autoGeneratedColumns.map((col) => (
            <div
              key={col.id}
              style={{
                width: '360px',
                minWidth: '360px',
                maxWidth: '360px',
                flexShrink: 0,
                flexGrow: 0
              }}
            >
              <KanbanColumn
                stage={col}
                records={col.list}
                moduleConfig={moduleConfig}
                activePipelineStages={activePipelineStages}
                isFilterActive={isFilterActive}
                onViewRecord={onViewRecord}
                onEditRecord={onEditRecord}
                onArchiveRecord={onArchiveRecord}
                onMoveStage={onMoveStage}
                canManage={canManage}
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
