name: omniflow_telecalling_app
description: "OmniFlow EMS Flutter Companion App for SIM Call Recording & Real-Time CRM Sync"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  permission_handler: ^11.3.1
  http: ^1.2.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
